os: linux
dist: xenial

language: r

r_packages:
  - devtools
  - rnaturalearthdata
  - rgeos
  - pkgdown
  - remotes

before_script:
 - Rscript -e "devtools::install_deps()"

warnings_are_errors: false

before_install: |
  sudo apt-get -y install \
  build-essential \
  libcurl4-gnutls-dev \
  libxml2-dev \
  libssl-dev \
  libgdal-dev \
  bwidget \
  libgdal1-dev \
  libgeos-dev \
  libgeos++-dev \
  libgsl0-dev \
  libproj-dev \
  libspatialite-dev \
  netcdf-bin \
  libudunits2-dev \
  libmagick++-dev

cache: packages

script: make all

jobs:
  include:
  - r: release

# before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   on:
#     branch: master
#   local_dir: docs

after_success:
  - Rscript -e 'devtools::install()'
